spring:
  profiles:
    active: '@environment@'
  mail:
    host: #your email-host
    username: #your email
    password: #your password
  redis:
    database: 0
    host: #your redis-host
    port: 6379
    password: #your redis-pwd