spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Book_Manager
    username: root
    password: wbq123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
server:
  port: 80